### ISSUE TITLE
Key is invalid

### ISSUE THREAD

**Issue by gregsj** [matelang/jwt-go-aws-kms#11]
I've tried to use this with a RSA key stored in AWS KMS but get a key is invalid error. I can manually sign the tokens directly with KMS so I know the key isn't the problem.

**Comment by matelang** [comment]
Hi @gregsj ,

Can you please post an example on how are you using it?
Also, what error message are you exactly getting.

Thanks.

**Comment by matelang** [comment]
I will close this issue for lack of details.
If you are able to provide details feel free to reopen.
