### ISSUE TITLE
Unable to use with go-jwt/v4 

### ISSUE THREAD

**Issue by fams** [matelang/jwt-go-aws-kms#18]
I'm trying to use the library with go-jwt/v4 but due to different signature of KMSSigningMethod in v2 it's not working. 
Is there a way to go mod tidy import version 1.1.0 of library?
i think there is an error on version of go.mod in v1.
https://go.dev/doc/modules/version-numbers
```txt
require (
	github.com/aws/aws-sdk-go-v2/config v1.18.27
	github.com/aws/aws-sdk-go-v2/service/kms v1.22.2
	github.com/golang-jwt/jwt/v4 v4.5.0
	github.com/matelang/jwt-go-aws-kms/v2 v1.1.0
)
```
```bash
❯ go mod tidy
go: errors parsing go.mod:
/Users/fams/src/jws-signer/go.mod:9:2: require github.com/matelang/jwt-go-aws-kms/v2: version "v1.1.0" invalid: should be v2, not v1
```

**Comment by matelang** [comment]
Hi @fams ,

I'll have to check, sorry for the delay, I missed the notification from this issue.

**Comment by fams** [comment]
Yes, the RSA-PSS is the alg used by me

**Comment by matelang** [comment]
I will close this issue since I did not have time to backport that functionality to v4.
I will continue to maintain the compatibility with go-jwt v5 and AWS SDK version 2.
